version: '3.6'

services:
  analytics-db:
    container_name: 'it-job-analytics-db-mysql'
    image: mysql:8.0
    platform: linux/amd64
    command: --max-seeks-for-key=1
    restart: always
    volumes:
      - analytics_db_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  rabbitmq:
    container_name: 'it-job-rabbitmq'
    image: bitnami/rabbitmq:3.12.0
    hostname: rabbitmq
    volumes:
      - ./rabbitmq_create_objects.sh:/docker-entrypoint-initdb.d/rabbitmq_create_objects.sh
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  vacancies-db:
    container_name: 'it-job-vacancies-db-mongo'
    image: mongo:6.0.6
    volumes:
      - vacancies_db_volume:/data/db
      - ./mongodb_create_user.js:/docker-entrypoint-initdb.d/mongodb_create_user.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}

  rate-limiter:
    container_name: 'it-job-rate-limiter'
    image: jobmarket2024/rate-limiter:prod
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod

  vacancy-storage:
    container_name: 'it-job-vacancy-storage'
    image: jobmarket2024/vacancy-storage-service:prod
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod

  vacancy-import:
    container_name: 'it-job-vacancy-import'
    image: jobmarket2024/vacancy-import-service:prod
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_PROFILES_ACTIVE: prod

  telegram-notification:
    container_name: 'it-job-telegram-notification'
    image: jobmarket2024/telegram-notification:prod
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${BOT_NAME}
      SPRING_PROFILES_ACTIVE: prod

  scheduler:
    container_name: 'it-job-scheduler'
    image: jobmarket2024/scheduler-service:prod
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  analytics-builder:
    container_name: 'it-job-analytics-builder'
    image: jobmarket2024/analytics-builder-service:prod
    restart: always
    depends_on:
      - vacancies-db
      - analytics-db
      - rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      SPRING_PROFILES_ACTIVE: prod

  vacancy-notifier:
    container_name: 'it-job-vacancy-notifier'
    image: jobmarket2024/vacancy-notifier:prod
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_PROFILES_ACTIVE: prod

  rest-api:
    container_name: 'it-job-rest-api'
    image: jobmarket2024/rest-api-service:prod
    depends_on:
      - analytics-db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web-ui:
    container_name: 'it-job-web-ui'
    image: jobmarket2024/web-ui:prod
    ports:
      - 80:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod

  grafana:
    build: './grafana'
    container_name: 'it-job-grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  prometheus:
    image: prom/prometheus
    container_name: 'it-job-prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus

volumes:
  analytics_db_mysql_volume:
  vacancies_db_volume: