name: Deploy buy runner

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          envkey_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          envkey_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          envkey_RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
          envkey_RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          envkey_MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          envkey_MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          envkey_MONGO_USER: ${{ secrets.MONGO_USER }}
          envkey_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          envkey_MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          file_name: .env

      - name: pull images
        run: docker-compose -f docker-compose-prod.yaml pull

      - name: restart containers
        run: docker-compose -f docker-compose-prod.yaml up -d